### ISSUE TITLE
No height-field?

### ISSUE THREAD

**Issue by zwcloud** [bepu/bepuphysics1#4]
I searched for height field but didn't find it. So is there a height field implementation in bepuphysics?

**Comment by mcmonkey4eva** [comment]
Like a heightmap/terrain collider? If so, implementation class of relevance is here -> https://github.com/bepu/bepuphysics1/blob/master/BEPUphysics/CollisionShapes/TerrainShape.cs

**Comment by zwcloud** [comment]
Thanks. I will have a look at it.
