### ISSUE TITLE
NaN problem

### ISSUE THREAD

**Issue by KakCAT** [bepu/bepuphysics1#6]
I'm having a problem with BoxShap.RayTest function which under some special conditions gets a NaN.

I'm raycasting with (0,-1,0) to get the height of the terrain, this means that inverse direction goes to infinite.

https://github.com/bepu/bepuphysics1/blob/e0438719412e2eab8683d5ca65c1b0bb0e9b177a/BEPUphysics/CollisionShapes/ConvexShapes/BoxShape.cs#L214

This is probably not a problem and the code is thought with this Infinite in mind to happen (it'd have been catched much earlier) however my real problem is that in the next line, (-halfWidth - localOrigin.X) is exactly zero, giving t1 a NaN value and bringing caos to characters walking over that box.

https://github.com/bepu/bepuphysics1/blob/e0438719412e2eab8683d5ca65c1b0bb0e9b177a/BEPUphysics/CollisionShapes/ConvexShapes/BoxShape.cs#L215

This is also happening to me when checking the Z component (same situation) a few lines below.

Could you please suggest me what to do in order to fix this?  I think setting t1 to Infinite when NaN is detected (and do the same for t2, and all the other components) would be ok, but I'd like to check this with you, as I don't understand the implications this can take.

Thanks! :)

**Comment by RossNordby** [comment]
Probably something like c23c2af029d1555109b58fc38988d148c61f6f70- just backported v2's test. I'm super snoozey so let me know if I goofed something.

**Comment by KakCAT** [comment]
Thanks, I'll replace the code and test it with the game running for some days to see what happens.

If not, the patch I proposed to make t1,t2 infinity when that happens seems to be working, despite being rather ugly.

**Comment by KakCAT** [comment]
Hi! Sorry for the delay.

I've been testing the code and it fixes the problem, and everything else seems to work well too.

Only a minor problem: "hit = default;" in lines 233 and 267  gives an error because the project is configured to use C# 7.0 . I've replaced it with hit = new RayHit()

thanks!
