### ISSUE TITLE
Excuse me, I want to simulate the same result on multiple machines, is it deterministic?

### ISSUE THREAD

**Issue by tianyixin** [bepu/bepuphysics1#7]
Excuse me, I want to simulate the same result on multiple machines, is it deterministic?

**Comment by mcmonkey4eva** [comment]
Multi-machine determinism is hard to guarantee in general, especially with floating-point ops. You might be interested in: https://forum.bepuentertainment.com/viewtopic.php?f=9&t=2507&p=14217

Also, BEPUphysicsv2 exists now and might be better to look for ways to work with rather than this old v1.

**Comment by tianyixin** [comment]
> 通常很难保证多机确定性，特别是对于浮点运算。您可能对以下内容感兴趣：[https](https://forum.bepuentertainment.com/viewtopic.php?f=9&t=2507&p=14217) : [//forum.bepuentertainment.com/viewtopic.php?f=9&t=2507&p=14217](https://forum.bepuentertainment.com/viewtopic.php?f=9&t=2507&p=14217)
> 
> 此外，BEPUphysicsv2现在已经存在，并且可能会比旧的v1更好地寻找工作方式。

thanks
